name: Build Slumber Android APK and Bundle

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.5'

    - name: Setup Release Keystore
      run: |
        echo "MIIKpgIBAzCCClAGCSqGSIb3DQEHAaCCCkEEggo9MIIKOTCCBbAGCSqGSIb3DQEHAaCCBaEEggWdMIIFmTCCBZUGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFKE8pd7sWgkVnpYozCWEnyrLM3ShAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQgnYiyWQ8PYAkBhc1zQTWKQSCBNAuG0TVCSZ2quNvbO+7LbXn3T7A8LvsvtgK4I3wScAHelGGQdUW2IMbi6N+q305ertE4euw53ZPCwoKGabjnaV+Uus0zVMinu/ejddd0NHucUzEO/K4b2da+N/iKfU/LTXrdLu0zwNVeXe6f+yZYJ54DFpSohFNaG8PARwcy2lNmAfR90Oc3KGJ/HoQ0cclefjtp/mzELg6wgLHHU9BB2fzjL8etjm22CylZCa5WYp1hyAXrLcYiLnd7qS6KdRtEb1X0M16JzNco8+3kNNwkSNdUaJUoMrKc2P1Sr0co8iKTnlVSGsrpLFXI2ANUXJUgcSuXmd1ibDVmjVZoO3I/2SJ6sE9TAsrvu41d18VGoCBPkzGbJmqdnftG9aFdm/xjWZcZ/sMK7OwBE63gXJp/FcziVQBKa5c7HzVD77Z/1Ssw96viPUPkvTsWgUUWvKZgN7C7JhpyGSiWy84yQL8KGXvfXjn0F3C20c9Jwq8jNnFRD8IU203UhLD5E0BVTSCkfaO1GMw8uSyPaBmVMaiZdJek+v1xGUxYTCFiNP/EDJ2NO46I8+IKmQB5qazfI4EBvKZ7CyyqfMdEb5S+yVnYXtMMYw+rxivcjGprShUG0zd+y5WWKGAsD+cHaDz3XdYDTNaIW1QFnNiVvTQL+71TukmITuzH4KGz0Vggky+k9tPsH2b9JPxtGIe3U8HMlzVRcO/J6Vvp9vNQWTsr6PwsMY664XUQTswIHZ0elCtSnmfgWSEm9h1W8buWSPuEkeUG4LLPxtDNze9CeqPM85l7ZXDYN5qGMBgnJup8EgFReQlQWvRKQBcQ8Eh/SOOoQDJiwr+a81Qcl9+5kYYkjm6jJDAnaH85TN8mmO/3YX8PkSyyp3hI5+ktb/TzZ4gIw2QHh2lbkW780p8IskU8WPBqd7X2WdYfV6SANQ3jcToOtt5zXtX89YrVLKoAb17S9r78xvJTMxFgoG596yZKsgWeR3EMZfd0Yhahqdm27VBM9juOUncHliDohClhPpushDH9xF9sH0q0nI6JR8H4DKeDjCw/69RSlZiTpzZp8M4ha4y3iO0stY13rExN6gaELZnrSjPLndl1wVM7GpnX7I/uCUbI6m38xTzyG81xyScTsoScpOCT7SRuQ5BxYTRXKBCixNq07JSqpzOjJhNWyr1zEep4SgupilEDjvHaOV+CG/nYkBZv4lKHzZ+Upfc2OdH5GarIWY6al24bntqpMAdHKQJ/6lQlLH/p+tVUIGaPskYatylXvVVEUhajeXWDMrbEbJZ3UgBmX9HEXpbqM/6quCv7rkjAYDPJ73//TvK1M14K1VORLlyjFJ6SweES5QJaAYypwbV1Is0aj/ryEEc/EmbDw88GPDKU2YUSZgqBd2y7NAJ5EtmxrIB5RSzzSPPFRqy/dSyX5iPHUVbqZAYCPjO4Q7qM8r+Q29QSJkOMjaedt1gWwvNCjKNrQ/PYZBC5qpXynyau9zNXoRnI+MUS8OBRzkydJJOvphcCLJzy7cBpyahX/OOsjvwYGs8pBLE9LkOPTnmc+7zWwJu5AOZf8hpjO0kdMaUdhSelRxzTayCvEdvhALptuLeUBxBFnFfXz/bzB6pqxa05Iv9e4F+7C3wz+oQDpbI3obN/ij2UgOdMTFCMB0GCSqGSIb3DQEJFDEQHg4AcwBsAHUAbQBiAGUAcjAhBgkqhkiG9w0BCRUxFAQSVGltZSAxNzg5MjE0MDAzMjU2MIIEgQYJKoZIhvcNAQcGoIIEcjCCBG4CAQAwggRnBgkqhkiG9w0BBwEwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFKb3dBmho5ModFhIh4+kS6dcYgrcAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQakQzhG/2FbFeLbqxlTpPfICCA/Dmk7UTdZlpSJs0bBQ8KYbWbKIiC5CZUf2AH6maveXPMGcIfNXwRyRx66S0FQitOAOMYiq+++wwRidFN0ngopXjF/yQ4NWe7KeN2Tu/+qQf1avVIBqNebV+mzUP881KY+4AD8ENIQ0IvS253W02G+3rhm+3CCI+Il1E37oQB7v4/w3Xhsi4N8IEOBx3Qeppgj/gMN4+NFTE5s6G67TarIxI3ALyh4KSg/Bg4CG3hLFz625vubssPZ6qYf/QhJIN7YU/xQLhsrEOqDIyKX7s4PvplasYuQ4ozELa39j1xbwp1ZR7fDwF2bfnshS4p+WydzRhpQ9czPCvc6s+ny+MqnLQ4i19VHabXLuJM6Z9p2vluVpCfYCyvFjzDHfLwSVZEuhESWh51YFzhwiSV5MEd9SyRE5lsxlpUwiUk0I3w2cJHJBKnLpe/LItiMw134vPhVU5Cz0tbPiuuOXpUPppGIvf8pHVTc9fOAeiU/8oKvL2AXO8/ipPMeCogCNl36gyKTiQt8/h5qEAuLwgOd+dTPhltBqhI1Ib/lKrw7qsZQtvL0IW8iZK784Q10UiAcP4dDezbfrKMPWTiblegdhEeaDGFSI7ayzFAWCf5cCFHOs2972mJONqCi+QyegQxExowJM9e54hZHmij+cKu8PZqvMJMmKe/1L3Pslgxwau1C1h4rvgoJDnxzAMvRH7iYqbCUCDg26JYahVToaxBT4z4LL9inOoM3mw+yNGdvvY8E7lo/Ciz2CLqSNT/REPJ/kWp/8Q1COZD6iar00jjds0qzeX2bPJIQjDa5cro948W3nA1OHoqkZJHv4dA4Zl1HGhnKtAqjKOEvxhrQSPv+0LXnXXfVZxUs1ijix+6MBWPtfbjDTTZpsoE+EC+NWzJd67rOqY8qvxvQDBG9To/bvrtTldAC4Zylg49XX2dZPhj06dWADZRH7rsYQ8Kzeo6sIu0dlzjMtPotl2ZTcvJjk07pk11qrmdIzH3IcZWvedHWLn5BBxSHwzVLXmMoFdlsOlkn9DcOHHhGJtUDaUEQ9ePpMoVkrx9VI92G+7gcH7Ef433K5yLemcyKVI+F1imCxLRTEgC879s+MvgMXccYXGCz0tWufrpBW6UwBhz+CJM2ev7Bwgmzg0zTk/QnJbxWhFZUCgnUBUltvyfTBKjNt153Gj5nastolOQTEyZMSa8SqBuGiuXGeqVGW8KS2l2ldF2/2Cqp0ZrJ9WSNQEg7UzXCYfAErY/37WNjJGi2BRdk9cdgEG/8WGmoJGrdHeHAgv7nTdCA1UKuWfQ6iQ9Tm/Ahq9jwuvlQV5BEkmI7VQxOBKX+BsIAi/cpz/sSGe5GrYCfswTTAxMA0GCWCGSAFlAwQCAQUABCD3vhxEoo9R9tHlgDQdrmE11M5RkiodjG4u1LpZgCsrKQQUb5DDozHGb+yZ+UQbSewaGqD9D34CAicQ" | base64 --decode > app/slumber_release.jks

    - name: Build Signed Release AAB and Debug APK
      run: |
        gradle bundleRelease assembleDebug --stacktrace

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Slumber-Production-Builds
        path: |
          app/build/outputs/bundle/release/*.aab
          app/build/outputs/apk/debug/*.apk
